name: Appium
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # tentei ubuntu mas deu erro e indicou macos por conta de processamento
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28] 
        target: [default]
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: pip install appium-python-client selenium robotframework-appiumlibrary
      - name: Start Appium Server
        run:
          chmod +x ./scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh
      # - name: Run Appium Tests
      #   uses: reactivecircus/android-emulator-runner@v1
      #   with:
      #     api-level: ${{ matrix.api-level }}
      #     target: ${{ matrix.target }}
      #     arch: x86_64
      #     profile: Nexus 6
      #     run:
      #       adb install -t /apks/app-curso-appium.apk
      #     script: 
      #       robot tests/testesCadastrar.robot # Executando nossos testes

